const USER_SIGNUP = "USER_SIGNUP";
const USER_SIGNIN = "USER_SIGNIN";
const USER_LOGOUT = 'USER_LOGOUT';
const USER_AUTHENTICATE = "USER_AUTHENTICATE";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const INCREASE_CART_QUANTITY = "INCREASE_CART_QUANTITY";
const DECREASE_CART_QUANTITY = "DECREASE_CART_QUANTITY";
const CLEAR_CART = "CLEAR_CART";

export { USER_SIGNUP, USER_SIGNIN, USER_LOGOUT, USER_AUTHENTICATE, ADD_TO_CART, REMOVE_FROM_CART, INCREASE_CART_QUANTITY, DECREASE_CART_QUANTITY, CLEAR_CART };