const USER_SIGNUP = "USER_SIGNUP";
const USER_SIGNIN = "USER_SIGNIN";
const USER_LOGOUT = 'USER_LOGOUT';
const USER_AUTHENTICATE = "USER_AUTHENTICATE";

export { USER_SIGNUP, USER_SIGNIN, USER_LOGOUT, USER_AUTHENTICATE };